%% AUTO-GENERATED (internal helper) by generate_vUS_2D_erf_windowed_Jac.m on 03-Sep-2026 17:27:18.
%% Do not call directly or hand-edit -- use vUS_2D_erf_windowed_complex_Jac.m,
%% and re-run the generator script to update both.

function [g1,dg1_dvxgp,dg1_dvzgp,dg1_dF,dg1_dDC] = vUS_2D_erf_windowed_complex_Jac_raw(in1,tau,k0,in4,f_min,f_max)
%vUS_2D_erf_windowed_complex_Jac_raw
%    [G1,DG1_DVXGP,DG1_DVZGP,dg1_dF,dg1_dDC] = vUS_2D_erf_windowed_complex_Jac_raw(IN1,TAU,K0,IN4,F_MIN,F_MAX)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    03-Sep-2026 17:27:18

sigma1 = in4(1,:);
sigma2 = in4(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = k0.^2;
t3 = x1.^2;
t4 = x2.^2;
t5 = -f_max;
t6 = 1.0./sigma1.^2;
t7 = 1.0./sigma2.^2;
t8 = 1.0./tau;
t9 = sqrt(pi);
t10 = f_min+t5;
t11 = 1.0./t9;
t12 = t3.*t6;
t13 = t4.*t7;
t14 = 1.0./t10;
t15 = t12+t13;
t16 = 1.0./t15;
t17 = sqrt(t15);
t18 = 1.0./t17;
t20 = (f_min.*t17.*tau)./2.0;
t21 = (f_max.*t17.*tau)./2.0;
t25 = t2.*t4.*t16.*4.0;
t19 = t18.^3;
t22 = k0.*t18.*2.0i;
t26 = k0.*t18.*x2.*-2.0i;
t27 = -t25;
t24 = -t22;
t28 = exp(t27);
t29 = k0.*t6.*t19.*x1.*x2.*2.0i;
t30 = k0.*t13.*t19.*2.0i;
t31 = t20+t26;
t32 = t21+t26;
t33 = erfz(t31);
t34 = erfz(t32);
t35 = t31.^2;
t36 = t32.^2;
t37 = -t34;
t38 = -t35;
t39 = -t36;
t40 = exp(t38);
t41 = exp(t39);
t42 = t33+t37;
g1 = x4+t8.*t9.*t14.*t18.*t28.*t42.*x3;
if nargout > 1
    dg1_dvxgp = t8.*t9.*t14.*t18.*t28.*x3.*(t11.*t40.*(t29+(f_min.*t6.*t18.*tau.*x1)./2.0).*2.0-t11.*t41.*(t29+(f_max.*t6.*t18.*tau.*x1)./2.0).*2.0)-t6.*t8.*t9.*t14.*t19.*t28.*t42.*x1.*x3+t2.*t4.*t6.*t8.*t9.*t14.*t18.^5.*t28.*t42.*x1.*x3.*8.0;
end
if nargout > 2
    dg1_dvzgp = t8.*t9.*t14.*t18.*t28.*x3.*(t11.*t40.*(t24+t30+(f_min.*t7.*t18.*tau.*x2)./2.0).*2.0-t11.*t41.*(t24+t30+(f_max.*t7.*t18.*tau.*x2)./2.0).*2.0)-t8.*t9.*t14.*t18.*t28.*t42.*x3.*(t2.*t16.*x2.*8.0-t2.*t7.*t16.^2.*x2.^3.*8.0)-t7.*t8.*t9.*t14.*t19.*t28.*t42.*x2.*x3;
end
if nargout > 3
    dg1_dF = t8.*t9.*t14.*t18.*t28.*t42;
end
if nargout > 4
    dg1_dDC = 1.0;
end
end
