%% AUTO-GENERATED by generate_vUS_2D_erf_windowed_Jac.m on 03-Sep-2026 17:27:18.
%% Do not hand-edit -- re-run the generator script instead.
%% Public [g1, J] wrapper around vUS_2D_erf_windowed_complex_Jac_raw.m.

function [g1, J] = vUS_2D_erf_windowed_complex_Jac(x, tau, k0, sigma, f_min, f_max)
    tau = tau(:);
    if nargout > 1
        [g1, dvx, dvz, dF, dDC] = vUS_2D_erf_windowed_complex_Jac_raw(x, tau, k0, sigma, f_min, f_max);
        onesTau = ones(size(tau));
        J = [dvx.*onesTau, dvz.*onesTau, dF.*onesTau, dDC.*onesTau];
    else
        g1 = vUS_2D_erf_windowed_complex_Jac_raw(x, tau, k0, sigma, f_min, f_max);
    end
    g1 = g1(:) .* ones(size(tau));
end
