%% AUTO-GENERATED by generate_vUS_3D_erf_Jac.m on 03-Sep-2026 00:56:37.
%% Do not hand-edit -- re-run the generator script instead.
%% Public [g1, J] wrapper around vUS_3D_erf_complex_Jac_raw.m.

function [g1, J] = vUS_3D_erf_complex_Jac(x, tau, k0, sigma)
    tau = tau(:);
    if nargout > 1
        [g1, dvx, dvy, dvz, dF, dDC] = vUS_3D_erf_complex_Jac_raw(x, tau, k0, sigma);
        onesTau = ones(size(tau));
        J = [dvx.*onesTau, dvy.*onesTau, dvz.*onesTau, dF.*onesTau, dDC.*onesTau];
    else
        g1 = vUS_3D_erf_complex_Jac_raw(x, tau, k0, sigma);
    end
    g1 = g1(:) .* ones(size(tau));
end
