%% AUTO-GENERATED (internal helper) by generate_vUS_2D_erf_Jac_symbolic_compare.m on 01-Sep-2026 16:59:54.
%% Do not call directly -- use vUS_2D_erf_complex_Jac_symbolic.m.

function [g1,dg1_dvxgp,dg1_dvzgp,dg1_dF,dg1_dDC] = vUS_2D_erf_complex_Jac_symbolic_raw(in1,tau,k0,in4)
%vUS_2D_erf_complex_Jac_symbolic_raw
%    [G1,DG1_DVXGP,DG1_DVZGP,dg1_dF,dg1_dDC] = vUS_2D_erf_complex_Jac_symbolic_raw(IN1,TAU,K0,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Sep-2026 16:59:53

sigma1 = in4(1,:);
sigma2 = in4(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = k0.^2;
t3 = x1.^2;
t4 = x2.^2;
t5 = 1.0./sigma1.^2;
t6 = 1.0./sigma2.^2;
t7 = 1.0./tau;
t8 = sqrt(pi);
t9 = 1.0./t8;
t10 = t3.*t5;
t11 = t4.*t6;
t12 = t10+t11;
t13 = 1.0./t12;
t15 = sqrt(t12);
t14 = t13.^2;
t16 = 1.0./t15;
t18 = t15.*tau;
t19 = sqrt(t13);
t23 = t2.*t4.*t13.*4.0;
t17 = t16.^3;
t20 = 1.0./t19;
t21 = k0.*t16.*2.0i;
t24 = k0.*t16.*x2.*-2.0i;
t25 = exp(t23);
t27 = -t23;
t22 = t21.*x2;
t28 = exp(t27);
t29 = k0.*t11.*t17.*2.0i;
t30 = t18+t24;
t26 = erfz(t22);
t31 = erfz(t30);
t32 = t30.^2;
t33 = -t32;
t35 = t26+t31;
g1 = x4+(t7.*t8.*t19.*t28.*t35.*x3)./2.0;
if nargout > 1
    t34 = exp(t33);
    dg1_dvxgp = (t7.*t8.*t19.*t28.*x3.*(t9.*t34.*(t5.*t16.*tau.*x1+k0.*t5.*t17.*x1.*x2.*2.0i).*2.0-k0.*t5.*t9.*t17.*t25.*x1.*x2.*4.0i))./2.0-(t5.*t7.*t8.*1.0./t20.^3.*t28.*t35.*x1.*x3)./2.0+t2.*t4.*t5.*t7.*t8.*1.0./t20.^5.*t28.*t35.*x1.*x3.*4.0;
end
if nargout > 2
    dg1_dvzgp = (t7.*t8.*t19.*t28.*x3.*(t9.*t34.*(-t21+t29+t6.*t16.*tau.*x2).*2.0+t9.*t25.*(t21-t29).*2.0))./2.0-(t7.*t8.*t19.*t28.*t35.*x3.*(t2.*t13.*x2.*8.0-t2.*t6.*t14.*x2.^3.*8.0))./2.0-(t6.*t7.*t8.*1.0./t20.^3.*t28.*t35.*x2.*x3)./2.0;
end
if nargout > 3
    dg1_dF = (t7.*t8.*t19.*t28.*t35)./2.0;
end
if nargout > 4
    dg1_dDC = 1.0;
end
end
