%% Generate SCC job file for RF2IQ data processing
function JOBS_IQ2g1(datapath,filename0, g1Info, ProcsFileInfo)
jobfilename='IQ2g1.sh';
jobsavepath= '/projectnb/npbfus/s/Jianbo/CODE/BU-SCC/JOBS/';  % job.txt file save path
SubFunctionPath='/projectnb/npbfus/s/Jianbo/CODE/Functions'; % sub functions Path on SCC server
SCCFunctionPath='/projectnb/npbfus/s/Jianbo/CODE/BU-SCC/SCCFunctions'; % SCC submit function Path on SCC server
%% data processing and file information
tStart=g1Info(1);
nTau=g1Info(2);
nt=g1Info(3);
startSubFrame=ProcsFileInfo(1);
nSubFrame=ProcsFileInfo(2);
startFile=ProcsFileInfo(3);
nFile=ProcsFileInfo(4);

fileinfo=strsplit(filename0,'-');
%% SCC node/core request 
pathInfo=strsplit(datapath,'/');
jobname=[pathInfo{end-1},'-',filename0];
prompt2={'# jobs','# cores per job','Memory per core','wall time','job name','email notify? (Y/N)'};
inputSCCinfo=inputdlg(prompt2,'SCC request parameter', 1,{num2str(nSubFrame),'2','8','6',jobname,'N'});
Njobs=(inputSCCinfo{1});       % number of jobs to be submitted for each file
Ncores=(inputSCCinfo{2});      % number of cores requested for each job
MemperCore=(inputSCCinfo{3});  % memory per core
WallTime=(inputSCCinfo{4});    % specify wall time
JobName=['RF2IQ-',inputSCCinfo{5}];              % Job name
EmailNote=inputSCCinfo{6};             % Email notify ?
if EmailNote=='Y' || EmailNote=='y'
    prompt4={'email address'};
    inputEmail=inputdlg(prompt4,'User email', 1,{'jianbo@bu.edu'});
    Emadd=(inputEmail{1});       % user's email address
    Emailinfo=['#$ -m ea','\n',...
        ['#$ -M ' Emadd],'\n'];
else
    Emailinfo=['\n'];
end

%% save IQ2g1 process information
fid=fopen([jobsavepath, jobfilename],'wt');
for ifile=startFile:startFile-1+nFile
    fileinfo{7}=num2str(ifile); 
    pathInfo{9}=strjoin(fileinfo(1:7),'-');
    idatapath=strjoin(pathInfo,'/');
    fileNameBase=[strjoin(fileinfo(1:8),'-'),'-'];
    fileNameTail=['-',strjoin(fileinfo(10:11),'-')];
    ifilename=[strjoin(fileinfo,'-')];
    JobName=['IQ2g1-',ifilename];
    job_cmd=['#! /bin/bash -l','\n'...
        ['#$ -pe omp ', Ncores],'\n',...
        ['#$ -l mem_per_core=',MemperCore,'G'], '\n',...
        ['#$ -l h_rt=',WallTime,':00:00'], '\n',...
        ['#$ -N ',JobName],'\n',...
        ['#$ -t 1-', Njobs],'\n',...
        Emailinfo,...
        'module load matlab/2017a','\n',...
        ['matlab -nodisplay -r ',...
        '"diary on; '...
        'addpath(''',SCCFunctionPath,'''); '...
        'addpath(''',SubFunctionPath,'''); ',...
        'datapath=''', idatapath,'''; ',...
        'g1Info=[', num2str(g1Info), ']; ',...
        'iSubFrame=$SGE_TASK_ID; ',...
        'fileNameBase=''',fileNameBase,''';',...
        'fileNameTail=''',fileNameTail,''';',...
        'filename=[fileNameBase, num2str(iSubFrame),fileNameTail]; ',...
        'SCC_IQ2g1(datapath, filename,g1Info); ',...
        'diary off; exit"'],'\n\n'];
    fprintf(fid,job_cmd);
    
end
fclose(fid);
%%

%% save RF2IQ process information in data folder

for ifile=startFile:startFile-1+nFile
    fileinfo{7}=num2str(ifile); 
    pathInfo{9}=strjoin(fileinfo(1:7),'-');
    idatapath=strjoin(pathInfo,'/');
    
    fid=fopen([idatapath, jobfilename],'wt');
    fileNameBase=[strjoin(fileinfo(1:8),'-'),'-'];
    fileNameTail=['-',strjoin(fileinfo(10:11),'-')];
    ifilename=[strjoin(fileinfo,'-')];
    JobName=['IQ2g1-',ifilename];
    job_cmd=['#! /bin/bash -l','\n'...
        ['#$ -pe omp ', Ncores],'\n',...
        ['#$ -l mem_per_core=',MemperCore,'G'], '\n',...
        ['#$ -l h_rt=',WallTime,':00:00'], '\n',...
        ['#$ -N ',JobName],'\n',...
        ['#$ -t 1-', Njobs],'\n',...
        Emailinfo,...
        'module load matlab/2017a','\n',...
        ['matlab -nodisplay -r ',...
        '"diary on; '...
        'addpath(''',SCCFunctionPath,'''); '...
        'addpath(''',SubFunctionPath,'''); ',...
        'datapath=''', idatapath,'''; ',...
        'g1Info=[', num2str(g1Info), ']; ',...
        'iSubFrame=$SGE_TASK_ID; ',...
        'fileNameBase=''',fileNameBase,''';',...
        'fileNameTail=''',fileNameTail,''';',...
        'filename=[fileNameBase, num2str(iSubFrame),fileNameTail]; ',...
        'SCC_IQ2g1(datapath, filename,g1Info); ',...
        'diary off; exit"'],'\n\n'];
    fprintf(fid,job_cmd);
    fclose(fid);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(['Job IQ2g1.txt saved,', datestr(now,'DD:HH:MM')]);
disp(savepath);