%% Generate SCC job file for RF2IQ data processing
function JOBS_IQ2GG(datapath,filename0, PRSinfo)
jobfilename='IQ2GG.sh';
jobsavepath= PRSinfo.JobFolder;  % job.txt file save path
SubFunctionPath='/projectnb/npbfus/s/Jianbo/CODE/Functions'; % sub functions Path on SCC server
SCCFunctionPath='/projectnb/npbfus/s/Jianbo/CODE/BU-SCC/SCCFunctions'; % SCC submit function Path on SCC server
%% data processing and file information
% startSubFrame=ProcsFileInfo(1);
% nSubFrame=ProcsFileInfo(2);
% startFile=ProcsFileInfo(3);
% nFile=ProcsFileInfo(4);

fileInfo=strsplit(filename0,'-');
%% SCC node/core request 
pathInfo=strsplit(datapath,'/');
jobname=[pathInfo{end-1},'-',filename0];
prompt2={'# jobs','# cores per job','Memory per core','wall time','job name','email notify? (Y/N)'};
inputSCCinfo=inputdlg(prompt2,'SCC request parameter', 1,{num2str(PRSinfo.nFile*PRSinfo.nRPT),'2','8','6',jobname,'N'});
Njobs=(inputSCCinfo{1});       % number of jobs to be submitted for each file
Ncores=(inputSCCinfo{2});      % number of cores requested for each job
MemperCore=(inputSCCinfo{3});  % memory per core
WallTime=(inputSCCinfo{4});    % specify wall time
JobName=['IQ2vUS-',inputSCCinfo{5}];              % Job name
EmailNote=inputSCCinfo{6};             % Email notify ?
if EmailNote=='Y' || EmailNote=='y'
    prompt4={'email address'};
    inputEmail=inputdlg(prompt4,'User email', 1,{'jianbo@bu.edu'});
    Emadd=(inputEmail{1});       % user's email address
    Emailinfo=['#$ -m ea','\n',...
        ['#$ -M ' Emadd],'\n'];
else
    Emailinfo=['\n'];
end
%% save IQ2vUS process information
fileNameBase=[strjoin(fileInfo(1:6),'-'),'-',PRSinfo.FileNameBase];
fileNameTail='.mat';
StartFilename=[fileNameBase,num2str(PRSinfo.startFile),'-',num2str(PRSinfo.startRPT), fileNameTail];

JobName=['IQ2GG-',pathInfo{end-1},'-',filename0];
fid=fopen([jobsavepath, jobfilename],'wt');
%         'PRSinfo=[', PRSinfo, ']; ',...
if PRSinfo.startFile==0
    job_cmd=['#! /bin/bash -l','\n'...
        ['#$ -pe omp ', Ncores],'\n',...
        ['#$ -l mem_per_core=',MemperCore,'G'], '\n',...
        ['#$ -l h_rt=',WallTime,':00:00'], '\n',...
        ['#$ -N ',JobName],'\n',...
        ['#$ -t 1-',Njobs],'\n',...
        Emailinfo,...
        'module load matlab/2017a','\n',...
        ['matlab -nodisplay -r ',...
        '"diary on; '...
        'addpath(''',SCCFunctionPath,'''); '...
        'addpath(''',SubFunctionPath,'''); ',...
        'iJob=$SGE_TASK_ID; ',...
        'startRptFile=',num2str(PRSinfo.startRPT),';',...
        'nRptFile=',num2str(PRSinfo.nRPT),';',...
        'fileNameBase=''',fileNameBase,''';',...
        'fileNameTail=''',fileNameTail,''';',...
        'filename=[fileNameBase, ''-'',num2str(iJob),fileNameTail]; ',...
        'datapath=''', datapath,'''; ',...
        'SCC_IQ2GG(datapath, filename); ',...
        'diary off; exit"'],'\n\n'];
else
    job_cmd=['#! /bin/bash -l','\n'...
        ['#$ -pe omp ', Ncores],'\n',...
        ['#$ -l mem_per_core=',MemperCore,'G'], '\n',...
        ['#$ -l h_rt=',WallTime,':00:00'], '\n',...
        ['#$ -N ',JobName],'\n',...
        ['#$ -t 1-',Njobs],'\n',...
        Emailinfo,...
        'module load matlab/2017a','\n',...
        ['matlab -nodisplay -r ',...
        '"diary on; '...
        'addpath(''',SCCFunctionPath,'''); '...
        'addpath(''',SubFunctionPath,'''); ',...
        'iJob=$SGE_TASK_ID; ',...
        'Startfile=',num2str(PRSinfo.startFile),';',...
        'startRptFile=',num2str(PRSinfo.startRPT),';',...
        'nRptFile=',num2str(PRSinfo.nRPT),';',...
        'fileNameBase=''',fileNameBase,''';',...
        'fileNameTail=''',fileNameTail,''';',...
        'filename=[fileNameBase, num2str(ceil(iJob/nRptFile)+Startfile-1),''-'',num2str(startRptFile+iJob-(ceil(iJob/nRptFile)-1)*nRptFile-1),fileNameTail]; ',...
        'datapath=''', datapath,'''; ',...
        'SCC_IQ2GG(datapath, filename); ',...
        'diary off; exit"'],'\n\n'];
end
fprintf(fid,job_cmd);
fclose(fid);
save([datapath,'vUS-PRSinfo.mat'], 'PRSinfo')
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(['Job IQ2GG.sh saved,', datestr(now,'DD:HH:MM')]);
disp([datapath,filename0]);
%%
SavePath=['/',strjoin(pathInfo(1:end-2),'/'),'/RESULT-',pathInfo{end-1},'-GG/'];
if ~exist(SavePath)
    mkdir(SavePath);
end

%% Also save SCC job to SavePath
fid=fopen([SavePath, jobfilename],'wt');
fprintf(fid,job_cmd);
fclose(fid);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(['Job IQ2GG.txt saved,', datestr(now,'DD:HH:MM')]);
disp([datapath,filename0]);