%% Parameters for testing
v_xgp = 0.005; % m/s
v_zgp = 0.01; % m/s
% tau = (0:1/5000:20e-3).'; % s
tau = (0:1/50000:20e-3).'; % s
nTau = length(tau);
c0 = 1540; % m/s
fc = 15.625e6; % Hz
lambda0 = c0./fc; % m
k0 = 2*pi/lambda0; % m^-1
sigma = [58.9110, 73.9967].*1e-6; % Field-based 1/e PSF values (x, z) [m] for the L22-14v probe at 15.625 MHz and 17 angles from -10 to 10 deg. The y component is set to some arbitrary positive number but it won't really be used. (G:\My Drive\Data\PSF Simulations\L22-14v PSF sim - 17 angles from -10 to 10 deg)

F = 1; DC = 0;

%% Set the flow profile parameters and calculate the g1 model (single curve)
a = 0.8;
k = 2.5;
% fmin = 0;
% fmax = a^2 * (k + 2) ./ k;
[fmin, fmax] = calc_f_integration_limits(k, a);

% Calculate g1 model
g1 = zeros(length(tau), 1); % Initialize g1 vector
x = [v_xgp, v_zgp, F, DC, k, a]; % Parameter vector
% for ti = 1:length(tau)
%     t = tau(ti);
%     g1(ti) = integral(vUS_2D_num_vec(x, t, k0, sigma), fmin, fmax);
% end
g1 = integral(vUS_2D_num_vec(x, tau, k0, sigma), fmin, fmax, 'ArrayValued', true);

% plot result
figure; plot(tau, abs(g1), 'LineWidth', 2), xlabel('tau'); ylabel('|g1|')

%% Sweep over the flow profile parameters (only k for now)
a = 0.4;
k = [2:0.2:3];
% fmin = zeros(length(k), 1);
% fmax = a^2 * (k + 2) ./ k;

% Calculate g1 model
g1 = cell(length(k), 1);

for ki = 1:length(k)
    x = [v_xgp, v_zgp, F, DC, k(ki), a]; % Parameter vector
    [fmin, fmax] = calc_f_integration_limits(k(ki), a);
    % temp_g1 = zeros(length(tau), 1); % Initialize g1 vector
    % for ti = 1:length(tau)
    %     t = tau(ti);
    %     temp_g1(ti) = integral(vUS_2D_num_vec(x, t, k0, sigma), fmin(ki), fmax(ki));
    % end
    % g1{ki} = temp_g1;
    g1{ki} = integral(vUS_2D_num_vec(x, tau, k0, sigma), fmin, fmax, 'ArrayValued', true);
end

% Plot
figure; hold on
for ki = 1:length(k)
    plot(tau.*1e3, abs(g1{ki}), 'LineWidth', 2), xlabel('tau [ms]'); ylabel('|g1|'); title("|g1| at different values of k and a = " + num2str(a))
end
legend(num2str(k.'))

figure; hold on
for ki = 1:length(k)
    plot(g1{ki}, 'LineWidth', 2), title("g1 at different values of k and a = " + num2str(a))
end
axis equal; xlim([-1, 1]); ylim([-1, 1]); 
legend(num2str(k.'), 'Location', 'southeast')

%% Fit data generated by the model (just for testing)
tau_mask = (2:length(tau)).'; % Don't fit at tau = 0, which might result in a NaN

x_fit = cell(length(k), 1); % Initialize a cell array to store the fit parameter vectors
g1_fit = cell(length(k), 1); % Initialize a cell array to store the fit g1 values
for ki = 1:length(k)
    % g1_exp = g1_erf(tau_mask);
    % SNR_dB = 30;
    % SNR_dB = 100;
    % g1_exp = awgn(g1_erf(tau_mask), SNR_dB);
    g1_exp = g1{ki};
    g1_exp_split = [real(g1_exp), imag(g1_exp)]; % Can add noise if desired
    fun_new = @(x) vUS_2D_num_wrapper(x, tau(tau_mask), k0, sigma, true) - g1_exp_split(tau_mask, :);
    % fun_new = @(x) vUS_2D_OF(x, tau(tau_mask), k0, sigma, g1_exp_split);
    
    % Normal fitting bounds
    lb = [0, -50e-3, 0, 0, 2, 0];
    ub = [50e-3, 50e-3, 1, 1, 3, 1];
    x0 = [0.0001, 0.0001, 1, 0, 2.5, 1]; % v_xgp0, v_zgp0, F, DC, k, a guesses [m/s]

    % % Test for degeneracy: only allow v_xgp, F, DC to vary
    % lb = [0, v_zgp, 0, 0, 2, a];
    % ub = [Inf, v_zgp, 1, 1, 2, a];
    % x0 = [0.0001, v_zgp, 1, 0, 2, a]; % v_xgp0, v_zgp0, F, DC, k, a guesses [m/s]

    % % Test 2 for degeneracy: allow everything except k to vary
    % lb = [0, -Inf, 0, 0, 2, 0];
    % ub = [Inf, Inf, 1, 1, 2, 1];
    % x0 = [0.0001, 0.0001, 1, 0, 2, 1]; % v_xgp0, v_zgp0, F, DC, k, a guesses [m/s]
    
    opts = optimoptions('lsqnonlin', 'Display', 'off', 'SpecifyObjectiveGradient', false);
    x_fit{ki} = lsqnonlin(fun_new, x0, lb, ub, opts);
    g1_fit{ki} = vUS_2D_num_wrapper(x_fit{ki}, tau, k0, sigma, false);
end

% Plot fitting results
colors = lines(length(k));
% |g1|
figure; hold on
legend_text = cell(length(k)*2, 1);
for ki = 1:length(k)
    legend_text{(ki-1)*2 + 1} = "Data: k = " + num2str(k(ki));
    legend_text{(ki-1)*2 + 2} = "Fit";
end
for ki = 1:length(k)
    plot(tau.*1e3, abs(g1{ki}), '-', 'LineWidth', 1, 'Color', colors(ki, :))
    plot(tau.*1e3, abs(g1_fit{ki}), ':', 'LineWidth', 1.5, 'Color', colors(ki, :))
end
xlabel('tau [ms]'); ylabel('|g1|'); title('|g1| at different values of k')
legend(legend_text)

% Complex g1
figure; hold on; title('g1 at different values of k')
for ki = 1:length(k)
    plot(g1{ki}, '-', 'LineWidth', 1, 'Color', colors(ki, :))
    plot(g1_fit{ki}, ':', 'LineWidth', 1.5, 'Color', colors(ki, :))
end
axis equal; xlim([-1, 1]); ylim([-1, 1]); xlabel('Re[g1]'); ylabel('Im[g1]')
legend(legend_text, 'Location', 'southeast')
% % |g1|
% figure
% plot(tau(tau_mask).*1e3, abs(g1_exp), '-o', 'LineWidth', 2)
% hold on
% plot(tau.*1e3, abs(g1_fitted_erf), '-x', 'LineWidth', 2)
% hold off
% xlabel('Time lag [ms]')
% ylabel('|g1|')
% legend("Noisy model data: v_{xgp} = "+num2str(v_xgp*1e3)+" mm/s, v_{zgp} = "+num2str(v_zgp*1e3) + " mm/s", "Fit: v_{xgp} = "+num2str(x(1)*1e3)+"mm/s, v_{zgp} = "+num2str(x(2)*1e3) + " mm/s")
% title("Signal with Gaussian white noise added; SNR: " + num2str(SNR_dB) + " dB")
