%% Description:
%   Symbolically derives the analytic Jacobian of the windowed
%   (partial-volume) g1 model -- vUS_2D_erf_windowed_vec_split.m -- w.r.t.
%   its four FITTED parameters [v_xgp, v_zgp, F, DC]. f_min/f_max are
%   fixed inputs (like tau, k0, sigma), not fitted -- see
%   vUS_2D_erf_windowed_vec_split.m's header for why.
%
%   Same two-file design and 'Vectorize' omission as
%   generate_vUS_2D_erf_Jac.m, for the same reasons (dg1/dDC is an exact
%   constant that breaks matlabFunction's internal column concatenation;
%   'Vectorize' isn't a recognized option in this Symbolic Math Toolbox
%   version). Self-checks against finite differences of the
%   independently-written vUS_2D_erf_windowed_vec_split.m before use.
%
% Requires: Symbolic Math Toolbox

%% 1. Build the model symbolically
x     = sym('x', [4, 1], 'real');       % x = [v_xgp; v_zgp; F; DC]
sigma = sym('sigma', [2, 1], 'real');   % sigma = [sigma_x; sigma_z]
syms tau k0 f_min f_max real

v_xgp = x(1); v_zgp = x(2); Fp = x(3); DC = x(4);
sx = sigma(1); sz = sigma(2);

M = v_xgp^2/sx^2 + v_zgp^2/sz^2;
sqrtM = sqrt(M);

A_max = (tau*sqrtM/2)*f_max - 2*1i*k0*v_zgp/sqrtM;
A_min = (tau*sqrtM/2)*f_min - 2*1i*k0*v_zgp/sqrtM;

g1 = DC + Fp/(f_max-f_min) * sqrt(sym(pi))/(tau*sqrtM) * exp(-4*k0^2*v_zgp^2/M) * (erf(A_max) - erf(A_min));

%% 2. Symbolic Jacobian w.r.t. [v_xgp, v_zgp, F, DC] only (NOT f_min/f_max)
J = jacobian(g1, x);   % 1x4, complex-valued

%% 3. Generate the raw numeric code -- g1 + 4 SEPARATE Jacobian-column outputs
vUSDir = fileparts(mfilename('fullpath'));
rawFile = fullfile(vUSDir, 'vUS_2D_erf_windowed_complex_Jac_raw.m');
matlabFunction(g1, J(1), J(2), J(3), J(4), ...
    'File', rawFile, ...
    'Vars', {x, tau, k0, sigma, f_min, f_max}, ...
    'Outputs', {'g1', 'dg1_dvxgp', 'dg1_dvzgp', 'dg1_dF', 'dg1_dDC'}, ...
    'Optimize', true);

txt = fileread(rawFile);
txt = regexprep(txt, '(?<![A-Za-z0-9_])erf\(', 'erfz(');
banner = sprintf(['%%%% AUTO-GENERATED (internal helper) by generate_vUS_2D_erf_windowed_Jac.m on %s.\n', ...
    '%%%% Do not call directly or hand-edit -- use vUS_2D_erf_windowed_complex_Jac.m,\n', ...
    '%%%% and re-run the generator script to update both.\n\n'], char(datetime('now')));
fid = fopen(rawFile, 'w');
fwrite(fid, [banner, txt]);
fclose(fid);
fprintf('Generated %s\n', rawFile);

%% 4. Write the thin public wrapper: standard [g1, J] interface
outFile = fullfile(vUSDir, 'vUS_2D_erf_windowed_complex_Jac.m');
pubCode = sprintf([ ...
    '%%%% AUTO-GENERATED by generate_vUS_2D_erf_windowed_Jac.m on %s.\n', ...
    '%%%% Do not hand-edit -- re-run the generator script instead.\n', ...
    '%%%% Public [g1, J] wrapper around vUS_2D_erf_windowed_complex_Jac_raw.m.\n\n', ...
    'function [g1, J] = vUS_2D_erf_windowed_complex_Jac(x, tau, k0, sigma, f_min, f_max)\n', ...
    '    tau = tau(:);\n', ...
    '    if nargout > 1\n', ...
    '        [g1, dvx, dvz, dF, dDC] = vUS_2D_erf_windowed_complex_Jac_raw(x, tau, k0, sigma, f_min, f_max);\n', ...
    '        onesTau = ones(size(tau));\n', ...
    '        J = [dvx.*onesTau, dvz.*onesTau, dF.*onesTau, dDC.*onesTau];\n', ...
    '    else\n', ...
    '        g1 = vUS_2D_erf_windowed_complex_Jac_raw(x, tau, k0, sigma, f_min, f_max);\n', ...
    '    end\n', ...
    '    g1 = g1(:) .* ones(size(tau));\n', ...
    'end\n'], char(datetime('now')));
fid = fopen(outFile, 'w');
fwrite(fid, pubCode);
fclose(fid);
rehash path
fprintf('Generated %s\n', outFile);

%% 5. Self-check against finite differences of vUS_2D_erf_windowed_vec_split.m
sigma_test = [58.9110; 73.9967] * 1e-6;
k0_test    = 2*pi / (1540/15.625e6);
tau_test   = (1:40)' / 5000;
f_min_test = 0.4; f_max_test = 1.6;

testPoints = { ...
    [ 3e-3;   8e-3; 0.7; 0.05], 'typical flow'; ...
    [ 1e-4;   1e-4; 0.5; 0.05], 'near-stagnant (small M)'; ...
    [-5e-3;  15e-3; 0.9; 0.00], 'fast axial, negative vxgp'};

hList = [1e-2, 1e-3, 1e-4, 1e-5, 1e-6];
fprintf('\n%-32s %14s %14s\n', 'test point', 'max rel. err', 'max abs. err');
allPass = true;
for i = 1:size(testPoints, 1)
    x0 = testPoints{i, 1};
    [~, J_analytic] = vUS_2D_erf_windowed_complex_Jac(x0, tau_test, k0_test, sigma_test, f_min_test, f_max_test);

    bestRelErr = Inf(1, 4); bestAbsErr = Inf(1, 4);
    for h = hList
        for p = 1:4
            dx = zeros(4, 1);
            step = h * max(abs(x0(p)), 1e-6);
            dx(p) = step;
            g1_plus  = vUS_2D_erf_windowed_vec_split(x0 + dx, tau_test, k0_test, sigma_test, f_min_test, f_max_test);
            g1_minus = vUS_2D_erf_windowed_vec_split(x0 - dx, tau_test, k0_test, sigma_test, f_min_test, f_max_test);
            d = (g1_plus - g1_minus) / (2*step);
            fd_col = [d(:,1); d(:,2)];

            Jc = [real(J_analytic(:,p)); imag(J_analytic(:,p))];
            colScale = max(abs(fd_col));
            sig = abs(fd_col) > 1e-2 * colScale;
            relErr = abs(Jc(sig) - fd_col(sig)) ./ abs(fd_col(sig));
            bestRelErr(p) = min(bestRelErr(p), max(relErr));
            bestAbsErr(p) = min(bestAbsErr(p), max(abs(Jc - fd_col)));
        end
    end
    mRel = max(bestRelErr); mAbs = max(bestAbsErr);
    fprintf('%-32s %14.3e %14.3e\n', testPoints{i, 2}, mRel, mAbs);
    allPass = allPass && (mRel < 1e-3) && (mAbs < 1e-4);
end

if allPass
    fprintf('\nAll test points passed.\n');
else
    warning('One or more test points show large disagreement -- inspect before use.');
end
