%% Description:
%   3D analog of generate_vUS_2D_erf_Jac.m: symbolically derives the
%   analytic Jacobian of the new (Poiseuille / uniform-velocity-
%   distribution) g1 model -- vUS_3D_erf.m / vUS_3D_erf_vec_split.m --
%   w.r.t. its five free parameters [v_xgp, v_ygp, v_zgp, F, DC] (DC a
%   real additive offset), and auto-generates a fast numeric MATLAB
%   function via matlabFunction.
%
%   Run this script once (and again any time the model formula itself
%   changes) to (re)generate:
%       vUS_3D_erf_complex_Jac_raw.m  -- AUTO-GENERATED internal helper,
%           do not call directly or hand-edit
%       vUS_3D_erf_complex_Jac.m      -- AUTO-GENERATED public [g1,J]
%           interface, do not hand-edit
%   Then use the small hand-written wrappers vUS_3D_erf_vec_split_Jac.m
%   and vUS_3D_erf_residJac.m to plug into lsqnonlin.
%
%   Same two-file design as generate_vUS_2D_erf_Jac.m, for the same
%   reason: dg1/dDC is an exact constant (1), which matlabFunction
%   correctly simplifies away -- but that then makes a single
%   J=[col1,...,col5] concatenation crash, since a bare scalar doesn't
%   auto-broadcast against the other tau-length columns under horzcat.
%   Forcing a fake "+0*tau" dependency to dodge this gets optimized back
%   out by matlabFunction's own CSE pass (tested and confirmed for the 2D
%   case on R2025b / Symbolic Math Toolbox 25.2) -- so each column is
%   generated as its own separate output instead (no internal
%   concatenation at all), and the public wrapper below assembles +
%   explicitly broadcasts them. 'Vectorize' is intentionally omitted for
%   the same reason as the 2D generator: not a recognized matlabFunction
%   option in this Symbolic Math Toolbox version; elementwise (.^, .*,
%   ./) code generation is the default now.
%
%   v_xgp and v_ygp play IDENTICAL roles in this model -- both enter only
%   through M = v_xgp^2/sx^2 + v_ygp^2/sy^2 + v_zgp^2/sz^2, with no phase
%   information for either (same fundamental sign-ambiguity /
%   amplitude-only-sensitivity issue as v_xgp had in the 2D model, now
%   shared symmetrically by two components instead of one). v_zgp keeps
%   the more involved role (through M AND explicitly, via the phase term
%   and the exp(-4*k0^2*v_zgp^2/M) prefactor).
%
%   This script self-checks the generated Jacobian against finite
%   differences of the independently-written vUS_3D_erf_vec_split.m at a
%   few test points, including a near-stagnant-flow case (small M) --
%   the catastrophic-cancellation / large-dynamic-range regime identified
%   for the 2D model, which is structurally the same here since it comes
%   from k0*sigma, not from the number of velocity components.
%
% Requires: Symbolic Math Toolbox

%% 1. Build the model symbolically
x     = sym('x', [5, 1], 'real');       % x = [v_xgp; v_ygp; v_zgp; F; DC]
sigma = sym('sigma', [3, 1], 'real');   % sigma = [sigma_x; sigma_y; sigma_z]
syms tau k0 real

v_xgp = x(1); v_ygp = x(2); v_zgp = x(3); Fp = x(4); DC = x(5);
sx = sigma(1); sy = sigma(2); sz = sigma(3);

M = v_xgp^2/sx^2 + v_ygp^2/sy^2 + v_zgp^2/sz^2;

A = sqrt(M)*tau - 2*1i*k0*v_zgp/sqrt(M);
B = -2*1i*k0*v_zgp/sqrt(M);

g1 = DC + Fp/2 * sqrt(sym(pi)/M)/tau * exp(-4*k0^2*v_zgp^2/M) * (erf(A) - erf(B));

%% 2. Symbolic Jacobian w.r.t. [v_xgp, v_ygp, v_zgp, F, DC]
J = jacobian(g1, x);   % 1x5, complex-valued

%% 3. Generate the raw numeric code -- g1 + 5 SEPARATE Jacobian-column
% outputs (see header for why this avoids matlabFunction's internal
% concatenation crash).
vUSDir = fileparts(mfilename('fullpath'));
rawFile = fullfile(vUSDir, 'vUS_3D_erf_complex_Jac_raw.m');
matlabFunction(g1, J(1), J(2), J(3), J(4), J(5), ...
    'File', rawFile, ...
    'Vars', {x, tau, k0, sigma}, ...
    'Outputs', {'g1', 'dg1_dvxgp', 'dg1_dvygp', 'dg1_dvzgp', 'dg1_dF', 'dg1_dDC'}, ...
    'Optimize', true);

% Swap the symbolic 'erf' calls for the codebase's complex-safe 'erfz'
% (see generate_vUS_2D_erf_Jac.m's header for the full rationale).
txt = fileread(rawFile);
txt = regexprep(txt, '(?<![A-Za-z0-9_])erf\(', 'erfz(');
banner = sprintf(['%%%% AUTO-GENERATED (internal helper) by generate_vUS_3D_erf_Jac.m on %s.\n', ...
    '%%%% Do not call directly or hand-edit -- use vUS_3D_erf_complex_Jac.m,\n', ...
    '%%%% and re-run the generator script to update both.\n\n'], char(datetime('now')));
fid = fopen(rawFile, 'w');
fwrite(fid, [banner, txt]);
fclose(fid);
fprintf('Generated %s\n', rawFile);

%% 4. Write the thin public wrapper: standard [g1, J] interface (matching
% vUS_3D_erf_vec_split_Jac.m / vUS_3D_erf_residJac.m's expectations),
% with each Jacobian column explicitly broadcast to size(tau) before
% concatenation.
outFile = fullfile(vUSDir, 'vUS_3D_erf_complex_Jac.m');
pubCode = sprintf([ ...
    '%%%% AUTO-GENERATED by generate_vUS_3D_erf_Jac.m on %s.\n', ...
    '%%%% Do not hand-edit -- re-run the generator script instead.\n', ...
    '%%%% Public [g1, J] wrapper around vUS_3D_erf_complex_Jac_raw.m.\n\n', ...
    'function [g1, J] = vUS_3D_erf_complex_Jac(x, tau, k0, sigma)\n', ...
    '    tau = tau(:);\n', ...
    '    if nargout > 1\n', ...
    '        [g1, dvx, dvy, dvz, dF, dDC] = vUS_3D_erf_complex_Jac_raw(x, tau, k0, sigma);\n', ...
    '        onesTau = ones(size(tau));\n', ...
    '        J = [dvx.*onesTau, dvy.*onesTau, dvz.*onesTau, dF.*onesTau, dDC.*onesTau];\n', ...
    '    else\n', ...
    '        g1 = vUS_3D_erf_complex_Jac_raw(x, tau, k0, sigma);\n', ...
    '    end\n', ...
    '    g1 = g1(:) .* ones(size(tau));\n', ...
    'end\n'], char(datetime('now')));
fid = fopen(outFile, 'w');
fwrite(fid, pubCode);
fclose(fid);
rehash path
fprintf('Generated %s\n', outFile);

%% 5. Self-check: compare the analytic Jacobian against finite differences
% of the independently-written vUS_3D_erf_vec_split.m. Test points use
% the RC15gV matrix-probe PSF from test_vUS_3D_erf.m (a genuinely
% different geometry than the 2D L22-14v case -- larger, near-isotropic
% lateral sigma vs. a smaller axial sigma).
sigma_test = [429; 429; 126] * 1e-6;       % [m], RC15gV probe, from test_vUS_3D_erf.m
                                             % (column -- the symbolic-generated
                                             % function indexes in4(2,:), which
                                             % requires a column input)
k0_test    = 2*pi / (1540/15.625e6);       % [rad/m]
tau_test   = (1:40)' / 5000;               % [s], 5 kHz frame rate, tau1..tau40

testPoints = { ...
    [ 3e-3;  -4e-3;   8e-3; 0.7; 0.05], 'typical flow'; ...
    [ 1e-4;   1e-4;   1e-4; 0.5; 0.05], 'near-stagnant (small M)'; ...
    [-5e-3;   6e-3;  15e-3; 0.9; 0.00], 'fast axial, negative vxgp'};

hList = [1e-2, 1e-3, 1e-4, 1e-5, 1e-6];
fprintf('\n%-32s %14s %14s\n', 'test point', 'max rel. err', 'max abs. err');
allPass = true;
for i = 1:size(testPoints, 1)
    x0 = testPoints{i, 1};
    [~, J_analytic] = vUS_3D_erf_complex_Jac(x0, tau_test, k0_test, sigma_test);

    bestRelErr = Inf(1, 5);
    bestAbsErr = Inf(1, 5);
    for h = hList
        for p = 1:5
            dx = zeros(5, 1);
            step = h * max(abs(x0(p)), 1e-6);
            dx(p) = step;

            g1_plus  = vUS_3D_erf_vec_split(x0 + dx, tau_test, k0_test, sigma_test);
            g1_minus = vUS_3D_erf_vec_split(x0 - dx, tau_test, k0_test, sigma_test);
            d = (g1_plus - g1_minus) / (2*step);
            fd_col = [d(:,1); d(:,2)];

            Jc = [real(J_analytic(:,p)); imag(J_analytic(:,p))];

            colScale = max(abs(fd_col));
            sig = abs(fd_col) > 1e-2 * colScale;
            relErr = abs(Jc(sig) - fd_col(sig)) ./ abs(fd_col(sig));
            bestRelErr(p) = min(bestRelErr(p), max(relErr));
            bestAbsErr(p) = min(bestAbsErr(p), max(abs(Jc - fd_col)));
        end
    end

    mRel = max(bestRelErr); mAbs = max(bestAbsErr);
    fprintf('%-32s %14.3e %14.3e\n', testPoints{i, 2}, mRel, mAbs);
    allPass = allPass && (mRel < 1e-3) && (mAbs < 1e-4);
end

if allPass
    fprintf('\nAll test points passed (analytic vs. finite-difference of vUS_3D_erf_vec_split.m agree).\n');
else
    warning('One or more test points show large analytic-vs-finite-difference disagreement -- inspect before use.');
end
