%% AUTO-GENERATED by generate_vUS_2D_erf_Jac_symbolic_compare.m on 01-Sep-2026 16:59:54.
%% Public [g1, J] wrapper around vUS_2D_erf_complex_Jac_symbolic_raw.m.
%% This is a COMPARISON copy -- see vUS_2D_erf_complex_Jac.m for the
%% version actually wired into the fitting pipeline.

function [g1, J] = vUS_2D_erf_complex_Jac_symbolic(x, tau, k0, sigma)
    tau = tau(:);
    if nargout > 1
        [g1, dvx, dvz, dF, dDC] = vUS_2D_erf_complex_Jac_symbolic_raw(x, tau, k0, sigma);
        onesTau = ones(size(tau));
        J = [dvx.*onesTau, dvz.*onesTau, dF.*onesTau, dDC.*onesTau];
    else
        g1 = vUS_2D_erf_complex_Jac_symbolic_raw(x, tau, k0, sigma);
    end
    g1 = g1(:) .* ones(size(tau));
end
