%% AUTO-GENERATED (internal helper) by generate_vUS_3D_erf_Jac.m on 03-Sep-2026 00:56:37.
%% Do not call directly or hand-edit -- use vUS_3D_erf_complex_Jac.m,
%% and re-run the generator script to update both.

function [g1,dg1_dvxgp,dg1_dvygp,dg1_dvzgp,dg1_dF,dg1_dDC] = vUS_3D_erf_complex_Jac_raw(in1,tau,k0,in4)
%vUS_3D_erf_complex_Jac_raw
%    [G1,DG1_DVXGP,DG1_DVYGP,DG1_DVZGP,dg1_dF,dg1_dDC] = vUS_3D_erf_complex_Jac_raw(IN1,TAU,K0,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    03-Sep-2026 00:56:36

sigma1 = in4(1,:);
sigma2 = in4(2,:);
sigma3 = in4(3,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = k0.^2;
t3 = x1.^2;
t4 = x2.^2;
t5 = x3.^2;
t6 = 1.0./sigma1.^2;
t7 = 1.0./sigma2.^2;
t8 = 1.0./sigma3.^2;
t9 = 1.0./tau;
t10 = sqrt(pi);
t11 = 1.0./t10;
t12 = t3.*t6;
t13 = t4.*t7;
t14 = t5.*t8;
t15 = t12+t13+t14;
t16 = 1.0./t15;
t18 = sqrt(t15);
t17 = t16.^2;
t19 = 1.0./t18;
t21 = t18.*tau;
t22 = sqrt(t16);
t26 = t2.*t5.*t16.*4.0;
t20 = t19.^3;
t23 = 1.0./t22;
t24 = k0.*t19.*2.0i;
t27 = k0.*t19.*x3.*-2.0i;
t28 = exp(t26);
t30 = -t26;
t25 = t24.*x3;
t31 = exp(t30);
t32 = k0.*t14.*t20.*2.0i;
t33 = t21+t27;
t29 = erfz(t25);
t34 = erfz(t33);
t35 = t33.^2;
t36 = -t35;
t38 = t29+t34;
g1 = x5+(t9.*t10.*t22.*t31.*t38.*x4)./2.0;
if nargout > 1
    t37 = exp(t36);
    dg1_dvxgp = (t9.*t10.*t22.*t31.*x4.*(t11.*t37.*(t6.*t19.*tau.*x1+k0.*t6.*t20.*x1.*x3.*2.0i).*2.0-k0.*t6.*t11.*t20.*t28.*x1.*x3.*4.0i))./2.0-(t6.*t9.*t10.*1.0./t23.^3.*t31.*t38.*x1.*x4)./2.0+t2.*t5.*t6.*t9.*t10.*1.0./t23.^5.*t31.*t38.*x1.*x4.*4.0;
end
if nargout > 2
    dg1_dvygp = (t9.*t10.*t22.*t31.*x4.*(t11.*t37.*(t7.*t19.*tau.*x2+k0.*t7.*t20.*x2.*x3.*2.0i).*2.0-k0.*t7.*t11.*t20.*t28.*x2.*x3.*4.0i))./2.0-(t7.*t9.*t10.*1.0./t23.^3.*t31.*t38.*x2.*x4)./2.0+t2.*t5.*t7.*t9.*t10.*1.0./t23.^5.*t31.*t38.*x2.*x4.*4.0;
end
if nargout > 3
    dg1_dvzgp = (t9.*t10.*t22.*t31.*x4.*(t11.*t37.*(-t24+t32+t8.*t19.*tau.*x3).*2.0+t11.*t28.*(t24-t32).*2.0))./2.0-(t9.*t10.*t22.*t31.*t38.*x4.*(t2.*t16.*x3.*8.0-t2.*t8.*t17.*x3.^3.*8.0))./2.0-(t8.*t9.*t10.*1.0./t23.^3.*t31.*t38.*x3.*x4)./2.0;
end
if nargout > 4
    dg1_dF = (t9.*t10.*t22.*t31.*t38)./2.0;
end
if nargout > 5
    dg1_dDC = 1.0;
end
end
