%% AUTO-GENERATED (internal helper) by generate_vUS_3D_quad_Jac.m on 23-Sep-2026 18:22:55.
%% Do not call directly or hand-edit -- use vUS_3D_quad_complex_Jac.m,
%% and re-run the generator script to update.

function [E,dE_dvt,dE_dvz,dE_dk,dE_da] = vUS_3D_quad_complex_Jac_raw(in1,tau,k0,in4,s)
%vUS_3D_quad_complex_Jac_raw
%    [E,dE_dvt,dE_dvz,dE_dk,dE_da] = vUS_3D_quad_complex_Jac_raw(IN1,TAU,K0,IN4,S)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-Sep-2026 18:22:54

sigma1 = in4(1,:);
sigma3 = in4(3,:);
x1 = in1(1,:);
x2 = in1(2,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = log(s);
t3 = log(x6);
t4 = x6.^x5;
t5 = tau.^2;
t6 = x5+2.0;
t7 = x1.^2;
t8 = x2.^2;
t9 = 1.0./sigma1.^2;
t10 = 1.0./sigma3.^2;
t11 = x5-1.0;
t14 = x5./2.0;
t12 = t6.^2;
t13 = t4.*2.0;
t16 = x6.^t11;
t18 = s.^t14;
t19 = t7.*t9;
t20 = t8.*t10;
t15 = -t13;
t17 = t3.*t13;
t23 = t4.*t18;
t31 = t19+t20;
t21 = t6+t15;
t22 = t17-1.0;
t27 = t3.*t23;
t28 = t23-1.0;
t30 = (t2.*t23)./2.0;
t24 = 1.0./t21;
t29 = t28.^2;
t32 = t27+t30;
t25 = t24.^2;
t26 = t24.^3;
t33 = k0.*t6.*t24.*t28.*tau.*x2.*2.0i;
t34 = -t33;
t35 = (t5.*t12.*t25.*t29.*t31)./4.0;
t36 = -t35;
t37 = t34+t36;
t38 = exp(t37);
E = t38;
if nargout > 1
    dE_dvt = t5.*t9.*t12.*t25.*t29.*t38.*x1.*(-1.0./2.0);
end
if nargout > 2
    dE_dvz = -t38.*(k0.*t6.*t24.*t28.*tau.*2.0i+(t5.*t10.*t12.*t25.*t29.*x2)./2.0);
end
if nargout > 3
    dE_dk = -t38.*(k0.*t24.*t28.*tau.*x2.*2.0i+(t5.*t6.*t25.*t29.*t31)./2.0+k0.*t6.*t24.*t32.*tau.*x2.*2.0i+(t5.*t12.*t22.*t26.*t29.*t31)./2.0+(t5.*t12.*t25.*t28.*t31.*t32)./2.0+k0.*t6.*t22.*t25.*t28.*tau.*x2.*2.0i);
end
if nargout > 4
    dE_da = -t38.*(t5.*t12.*t16.*t26.*t29.*t31.*x5+k0.*t6.*t16.*t18.*t24.*tau.*x2.*x5.*2.0i+k0.*t6.*t16.*t25.*t28.*tau.*x2.*x5.*4.0i+t5.*t12.*t14.*t16.*t18.*t25.*t28.*t31);
end
end
