function [g1, J] = vUS_2D_erf_complex_Jac(x, tau, k0, sigma)
%% Description:
%   Value + analytic Jacobian for the new (Poiseuille / uniform-velocity-
%   distribution) g1 model -- vUS_2D_erf.m -- w.r.t. [v_xgp, v_zgp, F].
%
%   NOTE ON PROVENANCE: this file is meant to be AUTO-GENERATED by
%   generate_vUS_2D_erf_Jac.m using the Symbolic Math Toolbox. That
%   toolbox was not available where this was first written, so the
%   formulas below were derived and typed by hand instead, then
%   validated against finite differences of vUS_2D_erf_vec_split.m (see
%   validate_vUS_2D_erf_Jac.m -- max relative error reported there). If
%   you have Symbolic Math Toolbox access (e.g. via a campus license),
%   run generate_vUS_2D_erf_Jac.m once -- it will overwrite this file
%   with a symbolically-derived (and self-checked) version, which is the
%   more trustworthy long-term source of truth for this Jacobian.
%
%   Derivation sketch: write g1 = DC + P(tau) * Q(tau), where
%     M = v_xgp^2/sigma_x^2 + v_zgp^2/sigma_z^2
%     P = (F/2) * sqrt(pi/M) / tau * exp(-4*k0^2*v_zgp^2/M)   [real]
%     A = tau*sqrt(M) - i*2*k0*v_zgp/sqrt(M)
%     B = -i*2*k0*v_zgp/sqrt(M)
%     Q = erfz(A) - erfz(B)
%   v_xgp enters only through M; v_zgp enters through M AND explicitly
%   (in P's exponent and in A, B), so its derivative needs the full
%   multivariable chain rule (d/dvz|total = d/dvz|_M_fixed +
%   d/dM|_vz_fixed * dM/dvz). d(erf(z))/dz = (2/sqrt(pi))*exp(-z^2) holds
%   for complex z since erf is entire. DC is a real additive offset
%   (added directly to the complex g1), so d g1/dDC = 1 exactly --
%   equivalently d(Re g1)/dDC = 1, d(Im g1)/dDC = 0.
%
% Inputs:
%   x: [v_xgp, v_zgp, F, DC] (DC real-valued)
%   tau: vector of time lags [s]
%   k0: wavenumber [rad/m]
%   sigma: [sigma_x, sigma_z] [m]
%
% Outputs:
%   g1: complex, size(tau)
%   J: complex, [numel(tau), 4], columns = d g1 / d[v_xgp, v_zgp, F, DC]
%      (only computed if requested)

    v_xgp = x(1); v_zgp = x(2); Fp = x(3); DC = x(4);
    sx = sigma(1); sz = sigma(2);
    tau = tau(:);

    M = v_xgp^2/sx^2 + v_zgp^2/sz^2;
    sqrtM = sqrt(M);

    P = Fp/2 * sqrt(pi)/sqrtM ./ tau .* exp(-4*k0^2*v_zgp^2/M); % real, size(tau)
    A = tau.*sqrtM - 1i*2*k0*v_zgp/sqrtM;                        % size(tau)
    B = -1i*2*k0*v_zgp/sqrtM;                                    % scalar

    Q = erfz(A) - erfz(B); % size(tau)
    g1 = DC + P .* Q;

    if nargout > 1
        m_x = 2*v_xgp/sx^2; % dM/dv_xgp
        m_z = 2*v_zgp/sz^2; % dM/dv_zgp

        % --- dP/dvx, dP/dvz, dP/dF ---
        dP_dM_vzfixed = P .* (4*k0^2*v_zgp^2/M^2 - 1/(2*M));
        dP_dvz_Mfixed = P .* (-8*k0^2*v_zgp/M);

        dP_dvx = dP_dM_vzfixed * m_x;
        dP_dvz = dP_dvz_Mfixed + dP_dM_vzfixed * m_z;
        dP_dF  = P / Fp;

        % --- dA/dvx, dA/dvz and dB/dvx, dB/dvz ---
        dA_dM_vzfixed = tau/(2*sqrtM) + 1i*k0*v_zgp/M^1.5;
        dA_dvz_Mfixed = -1i*2*k0/sqrtM;
        dA_dvx = dA_dM_vzfixed * m_x;
        dA_dvz = dA_dvz_Mfixed + dA_dM_vzfixed * m_z;

        dB_dM_vzfixed = 1i*k0*v_zgp/M^1.5;
        dB_dvz_Mfixed = -1i*2*k0/sqrtM;
        dB_dvx = dB_dM_vzfixed * m_x;
        dB_dvz = dB_dvz_Mfixed + dB_dM_vzfixed * m_z;

        derf = @(z) 2/sqrt(pi) .* exp(-z.^2); % d(erf)/dz, valid for complex z

        dQ_dvx = derf(A).*dA_dvx - derf(B).*dB_dvx;
        dQ_dvz = derf(A).*dA_dvz - derf(B).*dB_dvz;

        dg1_dvx = dP_dvx .* Q + P .* dQ_dvx;
        dg1_dvz = dP_dvz .* Q + P .* dQ_dvz;
        dg1_dF  = dP_dF  .* Q; % Q has no F-dependence
        dg1_dDC = ones(size(tau)); % DC is an additive real offset

        J = [dg1_dvx, dg1_dvz, dg1_dF, dg1_dDC];
    end
end
